version: 2
endpoint: http://wasm.edgscan.live:8082
admin_secret: my_admin_secret_key
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://wasm.edgscan.live:3000
